name: Nix
on:
  pull_request:
    paths:
      - flake.nix
      - flake.lock
  push:
    paths:
      - flake.nix
      - flake.lock
jobs:
  nix--check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        if: ${{ !env.ACT }}
        uses: DeterminateSystems/magic-nix-cache-action@main

      - run: |
          nix flake check --all-systems
